### ISSUE TITLE
Warning: face reid gallery is empty!

### ISSUE THREAD

**Issue by Omaiwei-kun** [incluit/OpenVino-Driver-Behaviour#10]
Hi, I am using Ubuntu 18.4 in VM (Host Windows) after I followed all the step given, above warning come out when I try to run face detection, any idea why it is happen?

**Comment by brmarkus** [comment]
Have you followed the steps described in "6.1.5. Driver recognition" "https://github.com/incluit/OpenVino-Driver-Behaviour#615-driver-recognition", i.e. creating a "face gallery" for person/driver "recognition"?

**Comment by Omaiwei-kun** [comment]
![Capture](https://user-images.githubusercontent.com/65478357/85261993-ad637e80-b49f-11ea-9c0b-8e2b8baa565c.PNG)

This the output when i tried to run Face detection

**Comment by brmarkus** [comment]
Ok, the warning regarding empty face-(re-)identification seems not the reason the application is failing to run - but for whatever reason "memory could not be allocated".
Can you describe your platform and environment a bit? Are you memory constraint (very few system memory), like running on an embedded device or in a VM/container with very limited system memory being assigned?
Are you using your own pre-trained memory, which is very huge?

**Comment by Omaiwei-kun** [comment]
Currently I am using VirtualBox 6.1.10 Oracle VM to install Ubuntu in my laptop (Host OS is Windows). I installed the OpenVINO in Ubuntu 
![image](https://user-images.githubusercontent.com/65478357/85263986-96725b80-b4a2-11ea-905f-dc971fdced5b.png)

**Comment by brmarkus** [comment]
Can you try to find out the amount of system memory available in your VM, please? For whatever reason the CPU-plugin cannot allocate (not enough or not at all) memory in order to load the model.

**Comment by Omaiwei-kun** [comment]
![image](https://user-images.githubusercontent.com/65478357/85265222-88bdd580-b4a4-11ea-9e11-750129247cb1.png)

i have locatted about 4gb for base memory. u can refer at system

**Comment by Omaiwei-kun** [comment]
I have settled the issue, before this im using Ubuntu 18.4.4 and Openvino 2020.1... i change Ubuntu 18.04 and Openvino 2019 R3 and it worked.. Tq
