### ISSUE TITLE
unable to run thsi sample with MyriadX NCS2 stick on  Ras Pi 

### ISSUE THREAD

**Issue by initmahesh** [incluit/OpenVino-Driver-Behaviour#3]
Hi 
I compiled the sample by making following changes 
                
in file CmakeLists_common.cmake

_#   if("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
#        set (ARCH intel64)
#    else()
#        set (ARCH ia32)
#    endif()

#    set (BIN_FOLDER ${ARCH})
#endif()

if (NOT(BIN_FOLDER))
    if(CMAKE_SYSTEM_PROCESSOR STREQUAL "armv7l")
        set (ARCH armv7l)
    elseif("${CMAKE_SIZEOF_VOID_P}" EQUAL "8")
        set (ARCH intel64)
    else()
        set (ARCH ia32)
    endif()

    set (BIN_FOLDER ${ARCH})
endif()_

and then used below command to build for arm 

sudo cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=armv7-a" ../

it builds but when i run it fails and seems like it is looking x86 CPU with error below 

/my/OpenVino-Driver-Behaviour/build/armv7l/Release $ ./driver_behavior -m $face132 -i /usr/lib/scratch2/scratch_extensions/images/raspio-ports.jpg
InferenceEngine: 
	API version ............ 1.6
	Build .................. 23780
[ INFO ] Parsing input parameters
[ INFO ] Reading input
/opt/intel/openvino/deployment_tools/tools/model_downloader/Retail/object_reidentification/face/mobilenet_based/dldt/face-reidentification-retail-0095.xml
[ INFO ] Loading plugin CPU
[ ERROR ] Cannot find plugin to use :

**Comment by HernanG234** [comment]
Hi @initmahesh,
OpenVINO only runs on Intel's hardware. You can load a model into the MYRIAD but not on the arm cpu. You can read more on OpenVINO's docs. Try to run it on the vpu, with the appropiate `-d` flag.
Also, try to preview your message before sending it, to make it easier to read. You can quote or insert code with 
````
```
code here
```
````
You can search for markdown on google.
If you still have problems loading the models on the VPU, let us know.

Thanks!
