### ISSUE TITLE
couldn't make with opvino R1.0.1

### ISSUE THREAD

**Issue by fader111** [incluit/OpenVino-Driver-Behaviour#4]
Hi, nice project. But I couldn't make it. Use ubuntu 16.04 LTS and openvino toolkit _p_2019.1.133 (R1.0.1).  Making, I've got an error :
```
[ 94%] Building CXX object CMakeFiles/driver_behavior.dir/src/main.cpp.o
In file included from /home/at/OpenVino-Driver-Behaviour/src/main.cpp:23:0:
/home/at/OpenVino-Driver-Behaviour/src/detectors.hpp:30:22: error: ‘Core’ in namespace ‘InferenceEngine’ does not name a type
     InferenceEngine::Core * plugin;
```
what it can be?
I couldn't find any "Core" members in includes. Is the Openvino version wrong?

**Comment by HernanG234** [comment]
Yes, it's a versioning problem. Do `git checkout OpenVINO\<\=2019R1` and try to compile again. They broke the API in the 2019R2 version.

**Comment by fader111** [comment]
I use R1 not R2

**Comment by fader111** [comment]
The news after checkout:
```
[ 94%] Building CXX object CMakeFiles/driver_behavior.dir/src/main.cpp.o
In file included from /home/at/OpenVino-Driver-Behaviour/src/main.cpp:23:0:
/home/at/OpenVino-Driver-Behaviour/src/detectors.hpp:21:22: error: operator '>=' has no left operand
 #if (INTEL_CVSDK_VER >= INTEL_LAST_VER)
                      ^
In file included from /home/at/OpenVino-Driver-Behaviour/src/main.cpp:24:0:
/home/at/OpenVino-Driver-Behaviour/src/cnn.hpp:15:22: error: operator '>=' has no left operand
 #if (INTEL_CVSDK_VER >= INTEL_LAST_VER)
```

**Comment by HernanG234** [comment]
You have to
```
source scripts/setupenv.sh
```
**before running cmake**, please clean your build/ dir and start over.
Remember to download the models needed. We were working on providing a script to automate this but it's not finished yet. Follow the README and if you encounter any problems just ask.
Cheers!

**Comment by fader111** [comment]
now done! Many Thanks!!
