### ISSUE TITLE
not actually an Issue, just a Question - what SDK do you use?

### ISSUE THREAD

**Issue by fader111** [incluit/OpenVino-Driver-Behaviour#6]
Could you recommend, how to import the project and make proper settings in Eclipse, VS Code or any, and make then from IDE directly?
Thanks!

**Comment by HernanG234** [comment]
Hi @fader111,

Sorry for the late response. I personally work on vim and have a couple of scripts with the things I do most often. My colleague works on VS code, maybe he can give some tips on how to set it up but as far as I know he compiles everything from the command line anyway.

If you made some progress and want to contribute with this, you can always make a pull-request and we will be super happy.

Cheers!
