### ISSUE TITLE
make issues

### ISSUE THREAD

**Issue by nr-patel** [incluit/OpenVino-Driver-Behaviour#8]
While make, I am getting below error, any suggestions:

[  5%] Building NVCC (Device) object dlib_build/dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cusolver_dlibapi.cu.o
/usr/include/c++/7/bits/uses_allocator.h(138): error: "__is_uses_allocator_constructible_v" is not a function or static data member

/usr/include/c++/7/bits/uses_allocator.h(138): error: "constexpr" is not valid here

/usr/include/c++/7/bits/uses_allocator.h(152): error: "__is_nothrow_uses_allocator_constructible_v" is not a function or static data member

/usr/include/c++/7/bits/uses_allocator.h(151): error: "constexpr" is not valid here

/usr/include/c++/7/iomanip(460): error: "auto" function requires a trailing return type

/usr/include/c++/7/iomanip(469): error: "auto" function requires a trailing return type

/usr/include/c++/7/iomanip(479): error: "auto" function requires a trailing return type

/usr/include/c++/7/bits/stl_algobase.h(200): error: statement may not appear in a constexpr function

/usr/include/c++/7/bits/stl_algobase.h(202): error: a constexpr function must contain exactly one return statement

/usr/include/c++/7/bits/stl_algobase.h(224): error: statement may not appear in a constexpr function

/usr/include/c++/7/bits/stl_algobase.h(226): error: a constexpr function must contain exactly one return statement

/usr/include/c++/7/bits/char_traits.h(96): error: a constexpr function cannot have a nonliteral return type "void"
          detected during:
            instantiation of "void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_set_length(std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::size_type) [with _CharT=dlib::unichar, _Traits=std::char_traits<dlib::unichar>, _Alloc=std::allocator<dlib::unichar>]" 
/usr/include/c++/7/bits/basic_string.h(423): here
            instantiation of "std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::basic_string() [with _CharT=dlib::unichar, _Traits=std::char_traits<dlib::unichar>, _Alloc=std::allocator<dlib::unichar>]" 
/home/netra/OpenVino-Driver-Behaviour/third-party/dlib/dlib/cuda/../matrix/../unicode/unicode.h(501): here

12 errors detected in the compilation of "/tmp/tmpxft_00002033_00000000-6_cusolver_dlibapi.cpp1.ii".
CMake Error at dlib_generated_cusolver_dlibapi.cu.o.Release.cmake:279 (message):
  Error generating file
  /home/netra/OpenVino-Driver-Behaviour/build/dlib_build/dlib/CMakeFiles/dlib.dir/cuda/./dlib_generated_cusolver_dlibapi.cu.o

dlib_build/dlib/CMakeFiles/dlib.dir/build.make:617: recipe for target 'dlib_build/dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cusolver_dlibapi.cu.o' failed
make[2]: *** [dlib_build/dlib/CMakeFiles/dlib.dir/cuda/dlib_generated_cusolver_dlibapi.cu.o] Error 1
CMakeFiles/Makefile2:198: recipe for target 'dlib_build/dlib/CMakeFiles/dlib.dir/all' failed
make[1]: *** [dlib_build/dlib/CMakeFiles/dlib.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by HernanG234** [comment]
Hey @nr-patel,

You're trying to compile some NVIDIA stuff. It's a dlib problem and it's incompatible with what we're doing. Try to disable it with the proper compilation options on `third-party/dlib`. We don't have NVIDIA's GPUs so we didn't come across this kind of error.

It'd help us a lot if you can tweak dlib to make it work and submit a pull-request.

Cheers!
Hernán
