### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by qintian95** [incluit/OpenVino-Driver-Behaviour#9]
![image](https://user-images.githubusercontent.com/39986452/66796348-f2f7a100-ef39-11e9-86a8-f552d8a1e307.png)

**Comment by HernanG234** [comment]
Hey @qintian95,

[libao](https://xiph.org/ao/) is a cross-platform audio library. When you reach the drowsiness limit it'll start beeping, you should hear that. We run that on a loop, and there's some problem when we replay the file. It doesn't affect the behavior in any way, we could just remove the message. We will do soon. Thanks for reporting.

Cheers,
Hernán
